# Generated by Django 4.2.dev20221230122847 on 2023-01-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Causes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
    ]
